services:
  frontend:
    build:
      context: .
      args:
        VITE_API_URL: /api
        VITE_MAPBOX_ACCESS_TOKEN: ${VITE_MAPBOX_ACCESS_TOKEN}
    ports:
      - "8080:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
